export const validWords = [
 "cañón", "muñón", "bañar", "pañal", "sueño", "añejo", "perro", "gatos", "lente",
  "piano", "dulce", "fuego", "verde", "llama", "ratón", "flaco", "lento", "lunes", "nubes",
  "rumor", "cenar", "sello", "banco", "techo", "plomo", "bravo", "cosas", "leche", "hojas",
  "carta", "quema", "traje", "pases", "comen", "ancho", "creer", "andar", "sabio", "robar",
  "cazar", "mirar", "ojalá", "tenso", "ricos", "jugar", "nevar", "votar", "vuelo", "grano",
  "denso", "cerro", "limón", "bebés", "miedo", "vinos", "dólar", "tocar", "tigre",
  "negro", "vital", "temor", "justo", "plaza", "frito", "mojar", "pasar", "sueño", "ñoqui",
  "bañar", "gruñe", "saldo",
  "sabés", "duelo", "madre", "padre", "clase", "notas", "fresa", "barco", "bosque", "ciego",
  "huevo", "cielo", "nacer", "canal", "radio", "noche", "salto", "rival", "feliz",
  "veloz", "avión", "rayar", "juego", "rosas", "poema", "nubes", "lugar", "reiré", "bajar",
  "reloj", "sabio", "grupo", "estar", "dejar", "vuela", "brote", "botar", "plomo", "lucha",
  "campo", "punto", "presa", "bazar", "canes", "dedos", "razón", "tenis", "sudar", "sudor",
  "hondo", "calor", "diosa", "metas", "carta", "dolor", "cielo", "papel", "casas", "pobre",
  "altar", "canto", "ojera", "actor", "vidas", "noble", "pista", "rubor", "cabra", "árbol",
  "cazar", "lucha", "miedo", "clima", "orden", "surge", "verbo", "carga", "plato", "vapor",
  "truco", "magia", "rumba", "guapo", "vicio", "burla", "signo", "rompe", "lanza", "pisar",
  "banco", "silla", "tallo", "mover", "paseo", "menta", "amigo", "pagar", "andar", "llave",
  "sueño", "niñas", "añejo", "pardo", "marca", "harta", "nadar", "ruina", "temen", "picar",
  "lenta", "pasto", "bache", "cruce", "pelar", "alzar", "vacío", "picar", "votos", "decir",
  "mirar", "feliz", "nacer", "hojas", "pañal", "girar", "cerca", "duelo", "añico", "soñar",
  "plena", "bajar", "mojar", "teñir", "bañar", "sueña", "sitio", "ciclo",
  "mujer", "hijas", "padre", "amiga", "dudas", "trato", "norte", "surco", "botas", "lloro",
  "llena", "carne", "bruma", "tigre", "besos", "sello", "luzco", "duelo", "batir", "nubes",
  "pared", "queso", "monto", "gente", "fases", "señal", "rasgo", "brisa", "dulce", "terco",
  "sacar", "sabes", "venas", "temen", "ruego", "toque", "razón", "corta", "huelo",
  "deseo", "venir", "citar", "manos", "pasos", "cesta", "vasos", "brote", "dados",
  "sobra", "ñandú", "sueño", 
  "sonar", "canto", "palma", "pisos", "cuota", "ducha", "pelos", "resto", "truco", "jugar",
  "besar", "lleno", "copas", "línea", "criar", "volar", "trapo", "girar", "regar",
  "bañar", "sueña", "gruñe", "teñir",
  "fijar", "salsa", "junta", "rompe", "torre", "manía", "puñal", "gozar", "rogar", "botes",
  "ligar", "lomos", "salas", "fango", "cavar", "llevo", "andar", "peñas",
  "cañas", "rasca", "guapa", "chipá", "monas", "gruño", "tapar", "mirar", "vivir", "rojas","aeiou","áéíóú"
];
